Updated on 9.15.25

library(vegan)
library(tidyverse)
library(ggplot2)

#If Location Name, depth, and depth category is the same it is considered a replicate. 

#1 Data input and initial setup
metadata_input <- read_csv("~/R/Axial2023/datainput/axial_compiledmetadata_revised_samplestokeep.csv") %>%
  rename(sample = NEW_FASTQ_NAME)

ASV <- read.delim("C:/Users/alexis98adams/Documents/R/Axial2023/datainput/clean_ASV.tsv",
                  header = TRUE, sep = "\t")

#Metadata_input has been revised to only contain samples I want to include for this analysis
#Using samples in metadata_input select desired samples from ASV 
axial_asv <- ASV %>%
  column_to_rownames("FeatureID") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  filter(sample %in% rownames(metadata_input))

#2 Prepare ASV table for averaging across replicates
ASV_wDepth <- axial_asv %>%
  as.data.frame() %>%
  left_join(metadata_input %>% 
              select(sample, DEPTH, DEPTH_CATEGORY, Location_Name)) %>% 
  mutate(assoc_vent = case_when(
    (Location_Name == "ASHES") ~ "ASHES Plume",
    (Location_Name == "International District") ~ "International District Plume",
    (Location_Name == "Diva") ~ "International District Vent",
    (Location_Name == "Gollum") ~ "ASHES Vent",
    (Location_Name == "Marker 33") ~ "International District Vent",
    (Location_Name == "Marker 113") ~ "International District Vent",
    (Location_Name == "Anemone") ~ "ASHES Vent",
    (Location_Name == "Background") ~ "Background",
    (Location_Name == "Bag City") ~ "International District Vent",
    (Location_Name == "Vixen") ~ "International District Vent")) 

#3 Remove zero-ASV samples BEFORE averaging
ASV_wDepth <- ASV_wDepth %>%
  mutate(row_sum = rowSums(select(., where(is.numeric)))) %>%
  filter(row_sum != 0) %>%
  select(-row_sum)

# Keep original sample names for tracking
ASV_wDepth <- ASV_wDepth %>% column_to_rownames("sample")
ASV_wDepth$original_sample <- rownames(ASV_wDepth)

#4 Create DepthGroup for averaging replicates
ASV_wDepth <- ASV_wDepth %>% 
  mutate(new_SampleID = paste(assoc_vent, DEPTH_CATEGORY, DEPTH, sep = "_"))


#5 Average replicates. If new_SampleID is the same, average sequence count for each ASV
ASV_avg_reps <- ASV_wDepth %>%
  group_by(new_SampleID) %>%
  summarise(across(where(is.numeric), mean),
            samples_in_group = paste(original_sample, collapse = ", ")) %>%
  as.data.frame()

#####I calculated reps. slightly different this time. Rerun PERMANOVA and NMDS code just to be sure.
# Save DepthGroup as rownames for matrix calculations
rownames(ASV_avg_reps) <- ASV_avg_reps$new_SampleID

# keep samples_in_group for reference
samples_info <- ASV_avg_reps$samples_in_group

# Remove helper columns for NMDS
ASV_avg_reps <- ASV_avg_reps %>% select(-new_SampleID, -DEPTH, -samples_in_group)

# Convert to matrix for vegan
ASV_avg_reps_matrix <- as.matrix(ASV_avg_reps)

#6 Compute Bray-Curtis distance and run NMDS
set.seed(123)  # for reproducibility
axial_nmds <- metaMDS(ASV_avg_reps_matrix, distance = "bray")

#7 Extract NMDS scores and attach new_SampleID + sample tracking
axial_nmds_scores <- as.data.frame(scores(axial_nmds)$sites)
axial_nmds_scores$new_SampleID <- rownames(axial_nmds_scores)

# Merge sample tracking info
axial_nmds_scores <- axial_nmds_scores %>%
  left_join(data.frame(new_SampleID = rownames(ASV_avg_reps_matrix),
                       samples_in_group = samples_info),
            by = "new_SampleID")

#Extract original sample from each group of replicates to attach metadata that correspons to one representative sample
axial_nmds_scores <- axial_nmds_scores %>%
  mutate(first_sample = str_split(samples_in_group, ", ") %>% map_chr(1)) %>% 
  left_join(
    ASV_wDepth %>% 
      rownames_to_column("sample") %>%
      select(sample, assoc_vent),       
    by = c("first_sample" = "sample"))


#Plot NMDS
install.packages("ggrepel")
library(ggrepel)

ggplot(axial_nmds_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(fill = assoc_vent, shape = assoc_vent), size = 4, colour = "black") +
  geom_text_repel(aes(label = new_SampleID), size = 3, max.overlaps = 20) +
  scale_fill_manual(name = "Location Name", values = c(
    "ASHES Plume" = "firebrick2",
    "ASHES Vent" = "firebrick2",
    "International District Plume" = "darkcyan",
    "International District Vent" = "darkcyan",
    "Background" = "darkgoldenrod")) +
  scale_shape_manual(name = "Location Name", values = c(
    "ASHES Plume" = 21,
    "ASHES Vent" = 22,
    "International District Plume" = 21,
    "International District Vent" = 22,
    "Background" = 24)) +
  theme(
    axis.text.y = element_text(colour = "black", size = 12, face = "bold"),
    axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
    legend.text = element_text(size = 12, face ="bold", colour ="black"), 
    legend.position = "right",
    axis.title.y = element_text(face = "bold", size = 14), 
    axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
    legend.title = element_text(size = 14, colour = "black", face = "bold"), 
    panel.background = element_blank(), 
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1.2),
    legend.key = element_blank()
  ) +
  labs(x = "NMDS1", y = "NMDS2")

##ASHES PERMANOVA
#Subset data for just one vent site. (This can not be done once a distance object is created). 
#axial_ASV_final contains only ASVs from the samples we want to analyze, averaged across replicates, and any samples with zero ASVs have been removed. 

#1 prep ASV table 
asv_ASHES <- ASV_avg_reps %>% rownames_to_column("sample") %>% filter(grepl("ASHES", sample)) %>% 
  column_to_rownames("sample")

#Pull out ASHES data from metadata table created for NMDS scores
metadata_ASHES <- axial_nmds_scores %>% filter(grepl("ASHES", new_SampleID)) %>% 
  column_to_rownames("new_SampleID") %>% select(-NMDS1, -NMDS2)

rownames(asv_ASHES)
rownames(metadata_ASHES)

asv_ASHES <- asv_ASHES %>% rownames_to_column("samples_in_group") 
asv_ASHES <- asv_ASHES %>% select(-samples_in_group)

bray_curtis_ASHES <- vegdist(asv_ASHES, method = "bray")

#Run PERMANOVA using adonis2() in vegan 
adonis_results_ASHES <- adonis2(bray_curtis_ASHES ~ DEPTH_CATEGORY, data = metadata_ASHES, permutations = 9999)

#International District
#1 prep ASV table 
asv_intldist <- ASV_avg_reps %>% rownames_to_column("sample") %>% filter(grepl("International District", sample)) %>% 
  column_to_rownames("sample")

#Pull out data from metadata table created for NMDS scores
metadata_intldist <- axial_nmds_scores %>% filter(grepl("International District", new_SampleID)) %>% 
  column_to_rownames("new_SampleID") %>% select(-NMDS1, -NMDS2)

rownames(asv_intldist)
rownames(metadata_intldist)

asv_intldist <- asv_intldist %>% rownames_to_column("samples_in_group") 
asv_intldist <- asv_intldist %>% select(-samples_in_group)

bray_curtis_intldist <- vegdist(asv_intldist, method = "bray")

#Run PERMANOVA using adonis2() in vegan 
adonis_results_intldist <- adonis2(bray_curtis_intldist ~ DEPTH_CATEGORY, data = metadata_intldist, permutations = 9999)





